### ISSUE TITLE
Failed to load weights

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [ipazc/mtcnn#33]
When I tried to create an instance of MTCNN detector, something went wrong:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-be16e7eec9f4> in <module>
      3 
      4 img = cv2.imread("ivan.jpg")
----> 5 detector = MTCNN()
      6 
      7 for i in range(len(images)):

.../lib/python3.5/site-packages/mtcnn/mtcnn.py in __init__(self, weights_file, min_face_size, steps_threshold, scale_factor)
    193             self.__session = tf.Session(config=config, graph=self.__graph)
    194 
--> 195             weights = np.load(weights_file).item()
    196             self.__pnet = PNet(self.__session, False)
    197             self.__pnet.set_weights(weights['PNet'])

.../lib/python3.5/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    445             else:
    446                 return format.read_array(fid, allow_pickle=allow_pickle,
--> 447                                          pickle_kwargs=pickle_kwargs)
    448         else:
    449             # Try a pickle

.../lib/python3.5/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    690         # The array contained Python objects. We need to unpickle the data.
    691         if not allow_pickle:
--> 692             raise ValueError("Object arrays cannot be loaded when "
    693                              "allow_pickle=False")
    694         if pickle_kwargs is None:

ValueError: Object arrays cannot be loaded when allow_pickle=False
```

I googled a bit and now think that problem causes due to new versions of numpy (see this issue: https://github.com/tensorflow/tensorflow/issues/28102).

**Comment by ahmedelmahy** [comment]
Exactly. It works after adding  allow_pickle=True
https://github.com/ipazc/mtcnn/pull/32

**Comment by togelian** [comment]
I fixed it by changing line 195 in mtcnn.py to:
            weights = np.load(weights_file, allow_pickle=True).item()

Just in case any others have the same problem

**Comment by nyck33** [comment]
@togelian @ahmedelmahy @vBLFTePebWNi6c 
I just git cloned it to Colab and check `mtcnn.py` and although it looked like `allow_pickle=True`, I'm still getting the a similar error but in line 195 of `mtcnn.py`

```
Traceback (most recent call last):
  File "mtcnn-video.py", line 21, in <module>
    detector = MTCNN()
  File "/gdrive/My Drive/pixelation/mtcnn/mtcnn/mtcnn.py", line 195, in __init__
    weights = np.load(weights_file).item()
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```
Do you have any ideas on how to fix this?
