### ISSUE TITLE
Tensorflow Errored

### ISSUE THREAD

**Issue by BillStark001** [ipazc/mtcnn#6]
Traceback (most recent call last):
……
  File "……", line 16, in <module>
    detector_ = MTCNN()

  File "E:\Programs\Anaconda3\lib\site-packages\mtcnn\mtcnn.py", line 193, in __init__
    self.__pnet = PNet(self.__session, False)

  File "E:\Programs\Anaconda3\lib\site-packages\mtcnn\network.py", line 44, in __init__
    self._config()

  File "E:\Programs\Anaconda3\lib\site-packages\mtcnn\mtcnn.py", line 55, in _config
    padding='VALID', relu=False)

  File "E:\Programs\Anaconda3\lib\site-packages\mtcnn\layer_factory.py", line 123, in new_conv
    kernel = self.__make_var('weights', shape=[kernel_size[1], kernel_size[0], channels_input // group, channels_output])

  File "E:\Programs\Anaconda3\lib\site-packages\mtcnn\layer_factory.py", line 78, in __make_var
    return tf.get_variable(name, shape, trainable=self.__network.is_trainable())

  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)

  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)

  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)

  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)

  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))

ValueError: Variable pnet/conv1/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "E:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)

**Comment by ipazc** [comment]
Hello **BillStark001**, thank you for reporting the issue. Can you please post your tensorflow version so we can replicate the error?

**Comment by BillStark001** [comment]
My Tensorflow version is 1.3.0 (gpu version) using cudnn 6.5 and cuda 8.0.
Actually I was using ipython shell 6.1.0 (python 3.5.0, cpython also has the same problem) to run my script. For the first time I ran it, nothing went wrong, while the second time this error occured during reloading this module. 
My temporary solution is:
`try:
    assert d
except:
    from mtcnn.mtcnn import MTCNN
    d = MTCNN()`
