### ISSUE TITLE
ValueError: The channel dimension of the inputs should be defined. Found `None`.

### ISSUE THREAD

**Issue by georgemillo** [ipazc/mtcnn#64]
I'm trying to use this library to follow [this tutorial on face recognition](https://machinelearningmastery.com/how-to-perform-face-recognition-with-vggface2-convolutional-neural-network-in-keras/), but when I run the example code I get the error:

`ValueError: The channel dimension of the inputs should be defined. Found \`None\`.`

The following steps are sufficient to get the error:

```python
>>> from mtcnn.mtcnn import MTCNN
Using TensorFlow backend.
>>> MTCNN()
WARNING:tensorflow:From /Users/george/.conda/envs/keras/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /Users/george/.conda/envs/keras/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/george/.conda/envs/keras/lib/python3.7/site-packages/mtcnn/mtcnn.py", line 88, in __init__
    self._pnet, self._rnet, self._onet = NetworkFactory().build_P_R_O_nets_from_file(weights_file)
  File "/Users/george/.conda/envs/keras/lib/python3.7/site-packages/mtcnn/network/factory.py", line 123, in build_P_R_O_nets_from_file
    p_net = self.build_pnet()
  File "/Users/george/.conda/envs/keras/lib/python3.7/site-packages/mtcnn/network/factory.py", line 40, in build_pnet
    p_layer = Conv2D(10, kernel_size=(3, 3), strides=(1, 1), padding="valid")(p_inp)
  File "/Users/george/.conda/envs/keras/lib/python3.7/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/Users/george/.conda/envs/keras/lib/python3.7/site-packages/keras/layers/convolutional.py", line 132, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
```

I'm completely new to all of this and don't understand the error at all. What am I doing wrong?

mtcnn: 0.1.0
Python 3.7.5
MacOS 10.14.6
tensorflow 1.15.0

**Comment by georgemillo** [comment]
After some digging around in the Keras source code, I was able to fix the error by opening `~/.keras/keras.json` and changing the line `"image_data_format": "channels_first"` to `"image_data_format": "channels_first"`. I don't understand what I've done, but yay, progress?

(Of course, now I get another obscure error when trying to run the tutorial code, but I'm not sure if it has anything to do with MTCNN.)

The grind continues...
