### ISSUE TITLE
About example.py

### ISSUE THREAD

**Issue by xnholidayyy** [ipazc/mtcnn#65]
Hello, when I run example.py, an error come up:
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/xinan/PycharmProjects/mtcnn-master/example.py", line 27, in <module>
    from mtcnn import MTCNN
  File "/home/xinan/PycharmProjects/mtcnn-master/mtcnn/__init__.py", line 26, in <module>
    from mtcnn.mtcnn import MTCNN
  File "/home/xinan/PycharmProjects/mtcnn-master/mtcnn/mtcnn.py", line 37, in <module>
    from mtcnn.network.factory import NetworkFactory
  File "/home/xinan/PycharmProjects/mtcnn-master/mtcnn/network/factory.py", line 26, in <module>
    from keras.layers import Input, Dense, Conv2D, MaxPooling2D, PReLU, Flatten, Softmax
  File "/home/xinan/.conda/envs/face-mtcnn/lib/python3.4/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/xinan/.conda/envs/face-mtcnn/lib/python3.4/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/xinan/.conda/envs/face-mtcnn/lib/python3.4/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/xinan/.conda/envs/face-mtcnn/lib/python3.4/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/xinan/.conda/envs/face-mtcnn/lib/python3.4/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/xinan/.conda/envs/face-mtcnn/lib/python3.4/site-packages/keras/backend/tensorflow_backend.py", line 13, in <module>
    from tensorflow.python.keras.utils import tf_utils
ImportError: cannot import name 'tf_utils'

Process finished with exit code 1

And my enviorment is:
Keras (2.3.1)
mtcnn (0.1.0)
numpy (1.16.5)
opencv-python (4.1.1.26)
pip (9.0.1)
tensorflow-gpu (1.8.0)
I want to ask help, thanks a lot!

**Comment by ipazc** [comment]
Seems to be a compatibility problem between your keras and tensorflow versions.
Check it here: https://stackoverflow.com/questions/57985406/cannot-import-name-tf-utils-when-using-importing-keras

**Comment by xnholidayyy** [comment]
> Seems to be a compatibility problem between your keras and tensorflow versions.
> Check it here: https://stackoverflow.com/questions/57985406/cannot-import-name-tf-utils-when-using-importing-keras

Thanks a lot! When I downgrade keras to 2.2.0, it works well!!!
